# Generated by Django 5.2.3 on 2025-06-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.CharField(default='Client inconnu', max_length=100),
            preserve_default=False,
        ),
    ]
